#!/usr/bin/env python

Import('env')
Import('env_modules')

#if env['tools']:
#	SConscript('editor/icons/SCsub')

env_gdsdecomp = env_modules.Clone()
env_gdsdecomp.add_source_files(env.modules_sources, "*.cpp")

if env['tools']:
	env_gdsdecomp.add_source_files(env.modules_sources, "editor/*.cpp")
